messages:
  commands:
    start: "start"
    help: "help"
  response:
    start: "Привет, кидай ссылку и я отправлю тебе визуал соответствующей странички. Для более детальной информации можешь ввести команду '/help' или воспользоваться кнопкой меню."
    help: "Этот бот создан, чтобы ты мог проверять сомнительные или подозрительные ссылки. Просто кинь сюда ссылку и я покажу тебе, как выглядит страничка, которую ты опасаешься посетить."
    unknown_command: "Не знаю такой команды, но может быть однажды..." 
  errors:
    default: "Блин, произошла какая-то непонятная ошибка, возможно позже я смогу тебе помочь, но это не точно :)"
    non_url: "Гм, похоже ты скинул не ссылку, если ты уверен в обратном, то попробую привести её в более ссылочный формат."
